// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct EquippedData {
  bytes32 toolEntityId;
  uint8 side;
}

library Equipped {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "", name: "Equipped", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x7462000000000000000000000000000045717569707065640000000000000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0021020020010000000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (bytes32)
  Schema constant _keySchema = Schema.wrap(0x002001005f000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (bytes32, uint8)
  Schema constant _valueSchema = Schema.wrap(0x002102005f000000000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "ownerEntityId";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](2);
    fieldNames[0] = "toolEntityId";
    fieldNames[1] = "side";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config (using the specified store).
   */
  function register(IStore _store) internal {
    _store.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get toolEntityId.
   */
  function getToolEntityId(bytes32 ownerEntityId) internal view returns (bytes32 toolEntityId) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = ownerEntityId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (bytes32(_blob));
  }

  /**
   * @notice Get toolEntityId.
   */
  function _getToolEntityId(bytes32 ownerEntityId) internal view returns (bytes32 toolEntityId) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = ownerEntityId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (bytes32(_blob));
  }

  /**
   * @notice Get toolEntityId (using the specified store).
   */
  function getToolEntityId(IStore _store, bytes32 ownerEntityId) internal view returns (bytes32 toolEntityId) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = ownerEntityId;

    bytes32 _blob = _store.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (bytes32(_blob));
  }

  /**
   * @notice Set toolEntityId.
   */
  function setToolEntityId(bytes32 ownerEntityId, bytes32 toolEntityId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = ownerEntityId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((toolEntityId)), _fieldLayout);
  }

  /**
   * @notice Set toolEntityId.
   */
  function _setToolEntityId(bytes32 ownerEntityId, bytes32 toolEntityId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = ownerEntityId;

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((toolEntityId)), _fieldLayout);
  }

  /**
   * @notice Set toolEntityId (using the specified store).
   */
  function setToolEntityId(IStore _store, bytes32 ownerEntityId, bytes32 toolEntityId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = ownerEntityId;

    _store.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((toolEntityId)), _fieldLayout);
  }

  /**
   * @notice Get side.
   */
  function getSide(bytes32 ownerEntityId) internal view returns (uint8 side) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = ownerEntityId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint8(bytes1(_blob)));
  }

  /**
   * @notice Get side.
   */
  function _getSide(bytes32 ownerEntityId) internal view returns (uint8 side) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = ownerEntityId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint8(bytes1(_blob)));
  }

  /**
   * @notice Get side (using the specified store).
   */
  function getSide(IStore _store, bytes32 ownerEntityId) internal view returns (uint8 side) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = ownerEntityId;

    bytes32 _blob = _store.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint8(bytes1(_blob)));
  }

  /**
   * @notice Set side.
   */
  function setSide(bytes32 ownerEntityId, uint8 side) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = ownerEntityId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((side)), _fieldLayout);
  }

  /**
   * @notice Set side.
   */
  function _setSide(bytes32 ownerEntityId, uint8 side) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = ownerEntityId;

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((side)), _fieldLayout);
  }

  /**
   * @notice Set side (using the specified store).
   */
  function setSide(IStore _store, bytes32 ownerEntityId, uint8 side) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = ownerEntityId;

    _store.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((side)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get(bytes32 ownerEntityId) internal view returns (EquippedData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = ownerEntityId;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(bytes32 ownerEntityId) internal view returns (EquippedData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = ownerEntityId;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data (using the specified store).
   */
  function get(IStore _store, bytes32 ownerEntityId) internal view returns (EquippedData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = ownerEntityId;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = _store.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(bytes32 ownerEntityId, bytes32 toolEntityId, uint8 side) internal {
    bytes memory _staticData = encodeStatic(toolEntityId, side);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = ownerEntityId;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(bytes32 ownerEntityId, bytes32 toolEntityId, uint8 side) internal {
    bytes memory _staticData = encodeStatic(toolEntityId, side);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = ownerEntityId;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using individual values (using the specified store).
   */
  function set(IStore _store, bytes32 ownerEntityId, bytes32 toolEntityId, uint8 side) internal {
    bytes memory _staticData = encodeStatic(toolEntityId, side);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = ownerEntityId;

    _store.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(bytes32 ownerEntityId, EquippedData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.toolEntityId, _table.side);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = ownerEntityId;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(bytes32 ownerEntityId, EquippedData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.toolEntityId, _table.side);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = ownerEntityId;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct (using the specified store).
   */
  function set(IStore _store, bytes32 ownerEntityId, EquippedData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.toolEntityId, _table.side);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = ownerEntityId;

    _store.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(bytes memory _blob) internal pure returns (bytes32 toolEntityId, uint8 side) {
    toolEntityId = (Bytes.getBytes32(_blob, 0));

    side = (uint8(Bytes.getBytes1(_blob, 32)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (EquippedData memory _table) {
    (_table.toolEntityId, _table.side) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(bytes32 ownerEntityId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = ownerEntityId;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(bytes32 ownerEntityId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = ownerEntityId;

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Delete all data for given keys (using the specified store).
   */
  function deleteRecord(IStore _store, bytes32 ownerEntityId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = ownerEntityId;

    _store.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(bytes32 toolEntityId, uint8 side) internal pure returns (bytes memory) {
    return abi.encodePacked(toolEntityId, side);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(bytes32 toolEntityId, uint8 side) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(toolEntityId, side);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(bytes32 ownerEntityId) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = ownerEntityId;

    return _keyTuple;
  }
}
