// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

enum TerrainTypes {
  Unknown,
  Grass,
  Mountain,
  Forest
}

enum StructureTypes {
  Unknown,
  Settlement,
  SpawnSettlement,
  WoodenWall,
  GoldMine,
  GoldCache
}

enum CharacterTypes {
  Unknown,
  Male1,
  Male2,
  Male3,
  Female1,
  Female2,
  Female3,
  Pirate1
}

enum QuestTypes {
  DAILY_CHECK_IN,
  DAILY_LOG_IN,
  GATHER_RESOURCE,
  COMMON_RESOURCE,
  RARE_RESOURCE,
  MYSTICAL_RESOURCE,
  ARTIFACT_RESOURCE,
  GOD_RESOURCE
}
