// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { SkyPoolConfig, SkyPoolConfigData } from "./tables/SkyPoolConfig.sol";
import { Admin } from "./tables/Admin.sol";
import { Name } from "./tables/Name.sol";
import { NameExists } from "./tables/NameExists.sol";
import { SeasonConfig, SeasonConfigData } from "./tables/SeasonConfig.sol";
import { WorldResourceS1 } from "./tables/WorldResourceS1.sol";
import { WorldQuestS1 } from "./tables/WorldQuestS1.sol";
import { PlayersActivity } from "./tables/PlayersActivity.sol";
import { PlayerPointS1 } from "./tables/PlayerPointS1.sol";
import { PlayerQuestS1, PlayerQuestS1Data } from "./tables/PlayerQuestS1.sol";
import { PlayerTreasureS1, PlayerTreasureS1Data } from "./tables/PlayerTreasureS1.sol";
import { PlayerQuestFinishedS1 } from "./tables/PlayerQuestFinishedS1.sol";
import { Character } from "./tables/Character.sol";
import { Recipes, RecipesData } from "./tables/Recipes.sol";
import { ReversePosition } from "./tables/ReversePosition.sol";
import { InventoryTool } from "./tables/InventoryTool.sol";
import { ReverseInventoryTool } from "./tables/ReverseInventoryTool.sol";
import { InventoryCount } from "./tables/InventoryCount.sol";
import { InventoryObjects } from "./tables/InventoryObjects.sol";
import { InventorySlots } from "./tables/InventorySlots.sol";
import { Equipped } from "./tables/Equipped.sol";
import { Stamina, StaminaData } from "./tables/Stamina.sol";
import { Health, HealthData } from "./tables/Health.sol";
import { PlayerActivity } from "./tables/PlayerActivity.sol";
import { LastKnownPosition, LastKnownPositionData } from "./tables/LastKnownPosition.sol";
import { PlayerMetadata, PlayerMetadataData } from "./tables/PlayerMetadata.sol";
import { Player } from "./tables/Player.sol";
import { SeasonPassIndex } from "./tables/SeasonPassIndex.sol";
import { SeasonPassConfig, SeasonPassConfigData } from "./tables/SeasonPassConfig.sol";
import { SeasonTimes, SeasonTimesData } from "./tables/SeasonTimes.sol";
import { SeasonPassLastSaleAt } from "./tables/SeasonPassLastSaleAt.sol";
import { SeasonPassSale, SeasonPassSaleData } from "./tables/SeasonPassSale.sol";
import { SeasonPass_Balances } from "./tables/SeasonPass_Balances.sol";
import { Position, PositionData } from "./tables/Position.sol";
import { GameToken } from "./tables/GameToken.sol";
