// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { QuestTypes } from "../common.sol";

/**
 * @title IQuestSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IQuestSystem {
  function dailyCheckIn() external;

  function gatherResource() external;

  function findTreasure() external;

  function confirmFinishedQuest(QuestTypes _type) external;
}
