// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { IBaseWorld } from "@latticexyz/world/src/codegen/interfaces/IBaseWorld.sol";
import { IAccountSystem } from "./IAccountSystem.sol";
import { ICharacterSystem } from "./ICharacterSystem.sol";
import { ILoginSystem } from "./ILoginSystem.sol";
import { IMineSystem } from "./IMineSystem.sol";
import { INameSystem } from "./INameSystem.sol";
import { IQuestSystem } from "./IQuestSystem.sol";
import { ISeasonPassSystem } from "./ISeasonPassSystem.sol";
import { IWorldSystem } from "./IWorldSystem.sol";

/**
 * @title IWorld
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @notice This interface integrates all systems and associated function selectors
 * that are dynamically registered in the World during deployment.
 * @dev This is an autogenerated file; do not edit manually.
 */
interface IWorld is
  IBaseWorld,
  IAccountSystem,
  ICharacterSystem,
  ILoginSystem,
  IMineSystem,
  INameSystem,
  IQuestSystem,
  ISeasonPassSystem,
  IWorldSystem
{}
